name: Cypress tests

on:
  workflow_dispatch:
    inputs:
      preview-url:
        description: The preview url
        type: string
        required: true

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install Dependencies
        run: npm install

      - name: Check the Preview URL
        run: echo ${{ github.event.inputs.preview-url }}
